-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.unassigned_guests_query()
    RETURNS TABLE(id integer, "firstName" text, "lastName" text, meal text, status text) 
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$

  select
    guests.id,
    guests."firstName",
    guests."lastName",
    guests.meal,
    guests.status
  from guests
    inner join reservations on guests."reservationId" = reservations.id
    left join "tableAssignments" on guests.id = "tableAssignments"."guestId"
  where "tableAssignments".id is null and 'dinner' = any(reservations.invitations)
  order by guests."firstName", guests."lastName" asc
$BODY$;

ALTER FUNCTION public.unassigned_guests_query()
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.unassigned_guests_query() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.unassigned_guests_query() TO anon;

GRANT EXECUTE ON FUNCTION public.unassigned_guests_query() TO authenticated;

GRANT EXECUTE ON FUNCTION public.unassigned_guests_query() TO postgres;

GRANT EXECUTE ON FUNCTION public.unassigned_guests_query() TO service_role;

ALTER TABLE IF EXISTS public."tableAssignments" DROP COLUMN IF EXISTS createdat;

ALTER TABLE IF EXISTS public."tableAssignments"
    ADD COLUMN "createdAt" timestamp with time zone DEFAULT now();
