-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE public.guests
    ALTER COLUMN "isVaccinated" TYPE boolean;
ALTER TABLE IF EXISTS public.guests
    ALTER COLUMN "isVaccinated" SET DEFAULT false;

ALTER TABLE public.guests
DROP CONSTRAINT "guests_reservationId_fkey",
ADD CONSTRAINT "guests_reservationId_fkey" FOREIGN KEY ("reservationId")
    REFERENCES public.reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE public.songs
DROP CONSTRAINT "songs_guestId_fkey",
ADD CONSTRAINT "songs_guestId_fkey" FOREIGN KEY ("guestId")
    REFERENCES public.guests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;